# configurations for LCNN model

# Parameters for training model
train_params:
  device: gpu
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1
  max_epochs: 10
  # Max time used for training (days:hours:mins:secs)
  max_time: "03:00:00:00"
  # Validate after every n batches
  val_check_interval: 1.0
  num_workers: 5
  gpus: 1
  savefile: "mfunet_model"
model:
  rainnet:
    input_shape: [512, 512, 5]
    kernel_size: 3
    mode: "regression"
    conv_shape:
      [
        ["1", [5, 64]],
        ["2", [64, 128]],
        ["3", [128, 256]],
        ["4", [256, 512]],
        ["5", [512, 1024]],
        ["6", [1536, 512]],
        ["7", [768, 256]],
        ["8", [384, 128]],
        ["9", [192, 64]],
      ]

  loss:
    name: "rmse"
    kwargs:
      alpha: 0.5
    discount_rate: 0.0
  train_leadtimes: 6
  display: 50
  apply_differencing: false
  lr: 1e-04
prediction:
  predict_leadtimes: 6
